# Generated by Django 5.2.4 on 2025-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_url_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace dirección'),
        ),
    ]
